import { Space, Card } from './types';

export const SPACES: Space[] = [
  { id: 0, name: 'Start Journey', type: 'go', description: 'Begin your adventure across the Nordic countries. Collect $200M as you pass.' },
  { id: 1, name: 'Tórshavn', type: 'property', color: '#8B4513', price: 60, rent: [2, 10, 30, 90, 160, 250], houseCost: 50, description: 'The cozy capital of the Faroe Islands, known for its turf-roofed houses.' },
  { id: 2, name: 'Community Chest', type: 'chest', description: 'Draw a card from the Community Chest for a surprise event.' },
  { id: 3, name: 'Nuuk', type: 'property', color: '#8B4513', price: 60, rent: [4, 20, 60, 180, 320, 450], houseCost: 50, description: 'The vibrant capital of Greenland, surrounded by stunning fjords.' },
  { id: 4, name: 'Income Tax', type: 'tax', price: 200, description: 'Pay your fair share of taxes to support the Nordic welfare model.' },
  { id: 5, name: 'DSB (Denmark)', type: 'railroad', price: 200, rent: [25, 50, 100, 200], description: 'The Danish State Railways, connecting the islands of Denmark.' },
  { id: 6, name: 'Aarhus', type: 'property', color: '#87CEEB', price: 100, rent: [6, 30, 90, 270, 400, 550], houseCost: 50, description: 'Denmark\'s second-largest city, famous for its modern architecture and history.' },
  { id: 7, name: 'Chance', type: 'chance', description: 'Take a chance and draw a card. Will it be good fortune or bad luck?' },
  { id: 8, name: 'Odense', type: 'property', color: '#87CEEB', price: 100, rent: [6, 30, 90, 270, 400, 550], houseCost: 50, description: 'The birthplace of Hans Christian Andersen, full of fairy-tale charm.' },
  { id: 9, name: 'Copenhagen', type: 'property', color: '#87CEEB', price: 120, rent: [8, 40, 100, 300, 450, 600], houseCost: 50, description: 'The bustling capital of Denmark, home to Nyhavn and bicycle culture.' },
  { id: 10, name: 'Nordic Prison', type: 'jail', description: 'Just visiting, or caught breaking the law? Time to serve your sentence.' },
  { id: 11, name: 'Turku', type: 'property', color: '#FF69B4', price: 140, rent: [10, 50, 150, 450, 625, 750], houseCost: 100, description: 'Finland\'s oldest city, situated on the southwest coast.' },
  { id: 12, name: 'Geothermal Energy', type: 'utility', price: 150, description: 'Harness the power of the earth, a key energy source in Iceland.' },
  { id: 13, name: 'Tampere', type: 'property', color: '#FF69B4', price: 140, rent: [10, 50, 150, 450, 625, 750], houseCost: 100, description: 'A major inland city in Finland, known for its industrial heritage and lakes.' },
  { id: 14, name: 'Helsinki', type: 'property', color: '#FF69B4', price: 160, rent: [12, 60, 180, 500, 700, 900], houseCost: 100, description: 'The capital of Finland, blending neoclassical architecture with modern design.' },
  { id: 15, name: 'VR Group (Finland)', type: 'railroad', price: 200, rent: [25, 50, 100, 200], description: 'The Finnish government-owned railway company.' },
  { id: 16, name: 'Akureyri', type: 'property', color: '#FFA500', price: 180, rent: [14, 70, 200, 550, 750, 950], houseCost: 100, description: 'The capital of North Iceland, nestled at the base of Eyjafjörður.' },
  { id: 17, name: 'Community Chest', type: 'chest', description: 'Draw a card from the Community Chest for a surprise event.' },
  { id: 18, name: 'Keflavík', type: 'property', color: '#FFA500', price: 180, rent: [14, 70, 200, 550, 750, 950], houseCost: 100, description: 'Home to Iceland\'s main international airport and rugged lava fields.' },
  { id: 19, name: 'Reykjavík', type: 'property', color: '#FFA500', price: 200, rent: [16, 80, 220, 600, 800, 1000], houseCost: 100, description: 'The northernmost capital in the world, famous for its vibrant culture and nature.' },
  { id: 20, name: 'Fika Break', type: 'parking', description: 'Take a well-deserved Swedish coffee break. Free parking!' },
  { id: 21, name: 'Trondheim', type: 'property', color: '#FF0000', price: 220, rent: [18, 90, 250, 700, 875, 1050], houseCost: 150, description: 'A historic Norwegian city, home to the spectacular Nidaros Cathedral.' },
  { id: 22, name: 'Chance', type: 'chance', description: 'Take a chance and draw a card. Will it be good fortune or bad luck?' },
  { id: 23, name: 'Bergen', type: 'property', color: '#FF0000', price: 220, rent: [18, 90, 250, 700, 875, 1050], houseCost: 150, description: 'The gateway to the fjords, known for its colorful Bryggen wharf.' },
  { id: 24, name: 'Oslo', type: 'property', color: '#FF0000', price: 240, rent: [20, 100, 300, 750, 925, 1100], houseCost: 150, description: 'The capital of Norway, surrounded by forests and the Oslofjord.' },
  { id: 25, name: 'Vy (Norway)', type: 'railroad', price: 200, rent: [25, 50, 100, 200], description: 'The Norwegian state railway, offering scenic journeys across the country.' },
  { id: 26, name: 'Malmö', type: 'property', color: '#FFFF00', price: 260, rent: [22, 110, 330, 800, 975, 1150], houseCost: 150, description: 'A coastal city in southern Sweden, linked to Copenhagen by the Øresund Bridge.' },
  { id: 27, name: 'Gothenburg', type: 'property', color: '#FFFF00', price: 260, rent: [22, 110, 330, 800, 975, 1150], houseCost: 150, description: 'Sweden\'s second-largest city, known for its canals and leafy boulevards.' },
  { id: 28, name: 'Hydroelectric Plant', type: 'utility', price: 150, description: 'Clean, renewable energy powering the Nordic region.' },
  { id: 29, name: 'Stockholm', type: 'property', color: '#FFFF00', price: 280, rent: [24, 120, 360, 850, 1025, 1200], houseCost: 150, description: 'The capital of Sweden, spread across 14 islands connected by 50 bridges.' },
  { id: 30, name: 'Caught in a Blizzard', type: 'gotojail', description: 'A severe snowstorm has halted your journey. Go directly to jail!' },
  { id: 31, name: 'Lofoten Islands', type: 'property', color: '#008000', price: 300, rent: [26, 130, 390, 900, 1100, 1275], houseCost: 200, description: 'An archipelago in Norway known for its dramatic scenery and fishing villages.' },
  { id: 32, name: 'Lapland', type: 'property', color: '#008000', price: 300, rent: [26, 130, 390, 900, 1100, 1275], houseCost: 200, description: 'The vast, snowy northern region of Finland, home to Santa Claus and reindeer.' },
  { id: 33, name: 'Community Chest', type: 'chest', description: 'Draw a card from the Community Chest for a surprise event.' },
  { id: 34, name: 'Svalbard', type: 'property', color: '#008000', price: 320, rent: [28, 150, 450, 1000, 1200, 1400], houseCost: 200, description: 'A remote Norwegian archipelago in the Arctic Ocean, known for polar bears.' },
  { id: 35, name: 'SJ AB (Sweden)', type: 'railroad', price: 200, rent: [25, 50, 100, 200], description: 'The Swedish government-owned passenger train operator.' },
  { id: 36, name: 'Chance', type: 'chance', description: 'Take a chance and draw a card. Will it be good fortune or bad luck?' },
  { id: 37, name: 'Geirangerfjord', type: 'property', color: '#00008B', price: 350, rent: [35, 175, 500, 1100, 1300, 1500], houseCost: 200, description: 'One of Norway\'s most spectacular and famous fjords, a UNESCO World Heritage site.' },
  { id: 38, name: 'Luxury VAT', type: 'tax', price: 100, description: 'Pay the high value-added tax on your luxury goods.' },
  { id: 39, name: 'Northern Lights', type: 'property', color: '#00008B', price: 400, rent: [50, 200, 600, 1400, 1700, 2000], houseCost: 200, description: 'The aurora borealis, a breathtaking natural light display in the Arctic sky.' },
];

export const CHANCE_CARDS: Card[] = [
  { text: "Advance to Start Journey (Collect $200M)", action: { type: 'advance', to: 0 } },
  { text: "Advance to the last property", action: { type: 'advance', to: 39 } },
  { text: "Advance to nearest Railroad. If unowned, you may buy it. If owned, pay owner twice the rental.", action: { type: 'advance', to: 'nearest_railroad', rentMultiplier: 2 } },
  { text: "Advance to nearest Railroad. If unowned, you may buy it. If owned, pay owner twice the rental.", action: { type: 'advance', to: 'nearest_railroad', rentMultiplier: 2 } },
  { text: "Advance to nearest Utility. If unowned, you may buy it. If owned, throw dice and pay owner 10x.", action: { type: 'advance', to: 'nearest_utility', rentMultiplier: 10 } },
  { text: "Bank pays you dividend of $50M", action: { type: 'collect', amount: 50 } },
  { text: "Get out of Prison Free", action: { type: 'get_out_of_jail' } },
  { text: "Go back 3 spaces", action: { type: 'move_back', spaces: 3 } },
  { text: "Go directly to Prison", action: { type: 'gotojail' } },
  { text: "Make general repairs on all your properties: For each house pay $25M, for each hotel pay $100M", action: { type: 'repairs', house: 25, hotel: 100 } },
  { text: "Pay poor tax of $15M", action: { type: 'pay', amount: 15 } },
  { text: "Take a trip to the first Railroad. If you pass Start Journey, collect $200M", action: { type: 'advance', to: 5 } },
  { text: "Take a walk to the first light blue property. Advance token.", action: { type: 'advance', to: 11 } },
  { text: "You have been elected Chairman. Pay each player $50M", action: { type: 'pay_players', amount: 50 } },
  { text: "Your building loan matures. Receive $150M", action: { type: 'collect', amount: 150 } },
  { text: "You have won a competition. Collect $100M", action: { type: 'collect', amount: 100 } }
];

export const CHEST_CARDS: Card[] = [
  { text: "Advance to Start Journey (Collect $200M)", action: { type: 'advance', to: 0 } },
  { text: "Bank error in your favor. Collect $200M", action: { type: 'collect', amount: 200 } },
  { text: "Doctor's fees. Pay $50M", action: { type: 'pay', amount: 50 } },
  { text: "From sale of stock you get $50M", action: { type: 'collect', amount: 50 } },
  { text: "Get out of Prison Free", action: { type: 'get_out_of_jail' } },
  { text: "Go directly to Prison", action: { type: 'gotojail' } },
  { text: "Grand Opera Night. Collect $50M from every player", action: { type: 'collect_players', amount: 50 } },
  { text: "Holiday Fund matures. Receive $100M", action: { type: 'collect', amount: 100 } },
  { text: "Income tax refund. Collect $20M", action: { type: 'collect', amount: 20 } },
  { text: "It is your birthday. Collect $10M from every player", action: { type: 'collect_players', amount: 10 } },
  { text: "Life insurance matures. Collect $100M", action: { type: 'collect', amount: 100 } },
  { text: "Hospital Fees. Pay $50M", action: { type: 'pay', amount: 50 } },
  { text: "School fees. Pay $50M", action: { type: 'pay', amount: 50 } },
  { text: "Receive $25M consultancy fee", action: { type: 'collect', amount: 25 } },
  { text: "You are assessed for street repairs: Pay $40M per house and $115M per hotel", action: { type: 'repairs', house: 40, hotel: 115 } },
  { text: "You have won second prize in a beauty contest. Collect $10M", action: { type: 'collect', amount: 10 } },
  { text: "You inherit $100M", action: { type: 'collect', amount: 100 } }
];
